### PR TITLE
Better agency names

### LINKED ISSUE #88: Update Agency Names
- Users are not recognizing the agency names as they are, expecting them to be named differently. We should use the more common version of the name 

- Ex: Department of Defense **not** Defense Department, Office of Personnel Management **not** Personnel Management Office

### PR DESCRIPTION
**Pull request by ondrae**
Uses `raw_name` instead of the `name` for Agencies pulled from the Federal Register API. This is a better choice for most agencies, as the `raw_name` more closely matches the common name. 

Screen Shot 2020-12-23 at 11 57 16 AM

There are a few that don't match that, such as Bureau of Consumer Financial Protection, but on the whole `raw_name` is a better choice. I don't want to include a lot of custom code, I want to match what the API gives us, for maintainability.

This PR also, drops support for subcomponents without metadata in the API. We were trying to include the DoD's Office of the Secretary, yet there are a dozen or so Office of the Secretary's across agencies. The code to include was getting brittle and would break on any changes to those subcomponents in the API. A user can still search for "Secretary" against the "Agency Names" field, with the DoD selected, and get that same list.

### Deploy
- If approved, please don't squash this one. We may want [this commit](https://github.com/18F/all_sorns/pull/95/commits/9c524d54f189d3de4a33a7c894862695abbcc693) for later.
- Delete all the Agencies and repopulate them.
```
rails console
Agency.destroy_all
exit
rails federal_register:find_sorns
```

Closes #88

### CODE REVIEW

**Comment by igorkorenfeld** [comment]
I think the list on the side looks good. The CFPB might be one of the special cases because its official name is technically Bureau of Consumer Financial Protection. 

I did notice that the agency name that pulls in to the card is the `name` version rather than the `raw_name` version.  Could we make that `raw_name` too? This is an example from OPM: 

image

**Comment by ondrae** [comment]
Those names on the card are from a third(!) source of agency names within the API. `agency_names`

When I tried to switch the source before, I couldn't get it to play nice with the highlighting of search, but I think I've figured some new things out since the last attempt. Let's try again.

**Comment by ondrae** [comment]
@igorkorenfeld I switched out the agency names on the cards. Run `rails federal_register:find_sorns` again to see the changes.

**Comment by igorkorenfeld** [comment]
Still waiting on it to finish the initial pull, I can look over it when I am back or if @peterrowland has time next week?

**Review by peterrowland — APPROVED** [review]
Approved

**Pull request merged**
