### PR TITLE
Simplify deployment trigger

### PR DESCRIPTION
**Pull request by folksgl**
**Merging will cause deployment upon successful test run**

Removes the duplicate test job within the `deploy.yml` workflow file and simplifies workflow logic. Reformatted yaml files to remove some syntax warnings.

### CODE REVIEW

**Comment by ondrae** [comment]
I'll get to this tomorrow.

**Review by ondrae — APPROVED** [review]
This is great, thanks for showing us how to reference other workflow files. We had tried a few times and couldn't get it to work.

**Comment by ondrae** [comment]
Hey @folksgl this PR failed to deploy after merging. I reverted it in #188.

I wrote up an issue with all the clues I could find at a https://github.com/18F/all_sorns/issues/189 including the history of our attempts.

**Comment by folksgl** [comment]
@ondrae This was an oversight on my part. I removed the `build_and_test` job from the deployment workflow in favor of the `workflow_run` trigger, but I failed to remove the `needs: build_and_test` from the deployment job in the same file. That explains the failed deployment and the message `The workflow is not valid. The workflow must contain at least one job with no dependencies.` found [in the failed run](https://github.com/18F/all_sorns/actions/runs/640992328)

I'll have the fix in shortly.

**Pull request merged**
