### PR TITLE
Custom pagination

### PR DESCRIPTION
**Pull request by ondrae**
This PR adds a nicely designed pagination menu to the top and bottom of the list of card SORNs.

Screen Shot 2020-11-30 at 12 14 34 PM

It is a standard implementation of the [Kaminari gem](https://github.com/kaminari/kaminari).

### CODE REVIEW

**Comment by ondrae** [comment]
Add to the bottom also.

**Comment by ondrae** [comment]
@igorkorenfeld Okay I've added the pagination on the bottom too, with a little bit of margin-bottom.
Screen Shot 2020-11-30 at 12 11 15 PM

Kind of related, how many cards should we show per page? Right now it is 25, which feels like a lot. 10 is what we used for phase three.

**Comment by igorkorenfeld** [comment]
Woo, that's great, thanks for adding that. I agree, 10 per page seems like a good number.

**Review by peterrowland — APPROVED** [review]
reviewed, approved!

**Pull request merged**
