### PR TITLE
Only return exact matches

### LINKED ISSUE #82: [Bug] Resolve "Found In" Blanks
The "Found In" section is coming up blank in search results

image

To replicate:
- Open the tool and type in "Financial Audit" in the search box

AC
- [ ] Any result displayed has a Found In section with at least one match highlighted
- [ ] Added a test to detect this issue in the future

### PR DESCRIPTION
**Pull request by ondrae**
Only returns exact matches of multiword searches.

Screen Shot 2020-12-23 at 9 48 18 AM

When accepted, please squash and merge.

Closes #82

### CODE REVIEW

**Comment by peterrowland** [comment]
For the search hint text, I was thinking:

"Search for individual keywords (ex. 'SSN') or specific phrases (ex. "social security number")"

**Review by lauraGgit — CHANGES_REQUESTED** [review]
from a coding perspective this looks good. Per the comment thread in #82, we should update the search help text to  either "Search for SORNs by entering a keyword (find exact matches)" or "Search for SORNs by entering a keyword (will return exact matches)" so that users understand the expected behavior of excluding non-exact matches.

before merging

**Comment by ondrae** [comment]
This work for you @igorkorenfeld 
Screen Shot 2020-12-23 at 12 40 06 PM

**Comment by igorkorenfeld** [comment]
Works for me!

**Review by igorkorenfeld — APPROVED** [review]

**Comment by igorkorenfeld** [comment]
@peterrowland also feel free to update it to what you suggested if you think it's clearer and more plain language? Want to make sure your suggestion isn't lost in the thread here.

**Review by peterrowland — APPROVED** [review]
reviewed and approved

**Comment by ondrae** [comment]
I made the changes @lauraGgit requested. They are out for a while, so I'm going to override their pending request.

**Pull request merged**
