### PR TITLE
Add OWASP ZAP scan Github action

### PR DESCRIPTION
**Pull request by folksgl**

### CODE REVIEW

**Comment by folksgl** [comment]
Closes #273

**Review by peterrowland — APPROVED** [review]
Looks good to me, we will just have to change the target to the fpc domain once it's turned on.

**Comment by folksgl** [comment]
> Looks good to me, we will just have to change the target to the fpc domain once it's turned on.

Is this a requirement from security somewhere? If not, the cloud.gov domain will still work regardless of what other domains we attach to the service and should remain stable even after getting the 'official' one.

**Comment by peterrowland** [comment]
> > Looks good to me, we will just have to change the target to the fpc domain once it's turned on.
> 
> @peterrowland Is this a requirement from security somewhere? If not, the cloud.gov domain will still work regardless of what other domains we attach to the service and should remain stable even after getting the 'official' one.

@folksgl you are right, I forgot about that.

**Pull request merged**
