### PR TITLE
Simplify deployment trigger

### LINKED ISSUE #189: Have deploy workflow depend on Test workflow.
We've tried this twice and been bitten both times.

Four months ago we tried https://github.com/18F/all_sorns/pull/40/files and ran into this error at https://github.com/18F/all_sorns/actions/runs/362058000

We just repeated it https://github.com/18F/all_sorns/pull/181 and https://github.com/18F/all_sorns/actions/runs/640992328

Last time we just have the test workflow duplicated inside of the deploy workflow. Its ugly but we couldn't figure it out.

Our peers at https://github.com/18F/identity-give-ipp-idemia/blob/main/.github/workflows/deploy-dev.yaml have it working with successful deploys, based on the same set up we have like https://github.com/18F/identity-give-ipp-idemia/actions/runs/633048533. 

We should look closer to find if our syntax is off at all.

### PR DESCRIPTION
**Pull request by folksgl**
resolves #189

### CODE REVIEW

**Comment by folksgl** [comment]
Should be identical to the previous PR, with the exception of the removal of `needs: build_and_test` in the deploy.yaml file. This will address the dependency issue that caused the action to fail last time.

**Comment by folksgl** [comment]
First test run failed, but re-running the tests failed. See runs
https://github.com/18F/all_sorns/actions/runs/643171728
https://github.com/18F/all_sorns/actions/runs/643202173

Hoping this doesn't mean transient test failures?

**Review by ondrae — APPROVED** [review]
Alright, let's try this one. 🚢

**Comment by ondrae** [comment]
Hey @lauraGgit check this PR out for an example of how to reference another workflow in a Github action. We were so close when we tried.

**Comment by lauraGgit** [comment]
Ah! good to see!

**Pull request merged**
